name: lsds-kafka-lab

services:
  rules:
    build: rules
    ports:
      - "5001:8000"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092

  alarms:
    build: alarms
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip

networks:
  kafka-cluster_kafka-cluster-network:
    external: true
