services:
  namenode:
    build: namenode
    ports:
      - "8000:8000"

  datanode1:
    build: ./datanode
    ports:
      - "8001:8001"
    environment:
      - PORT=8001

  datanode2:
    build: ./datanode
    ports:
      - "8002:8002"
    environment:
      - PORT=8002

  datanode3:
    build: ./datanode
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
